'use strict';
/* ── PulseCap — Muscle Anatomy Database ── */

const MUSCLE_DB = {
  // NECK
  sternocleidomastoid: { id:'sternocleidomastoid', name:'Sternocleidomastoid', icon:'🔵', region:'neck', group:'Neck Flexors', origin:'Sternum (manubrium) and medial clavicle', insertion:'Mastoid process of temporal bone', function:'Neck flexion (bilateral), lateral flexion and contralateral rotation (unilateral); assists in forced inspiration', exercises:['Neck flexion','Lateral neck stretch','Head rotation','Chin tucks'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Neck strain','Torticollis','Whiplash'] },
  upper_trapezius: { id:'upper_trapezius', name:'Upper Trapezius', icon:'🔷', region:'neck', group:'Trapezius', origin:'External occipital protuberance, nuchal ligament, C7 spinous process', insertion:'Lateral third of clavicle, acromion', function:'Elevates scapula (shrugs), tilts and rotates head, assists in neck extension', exercises:['Barbell shrugs','Dumbbell shrugs','Upright rows','Neck extension'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Upper trap strain','Chronic tightness','Trigger points'] },
  splenius_capitis: { id:'splenius_capitis', name:'Splenius Capitis', icon:'🔵', region:'neck', group:'Neck Extensors', origin:'Nuchal ligament, spinous processes C7-T3', insertion:'Mastoid process, occipital bone', function:'Bilateral: neck extension. Unilateral: ipsilateral lateral flexion and rotation', exercises:['Neck extension','Plate neck extension','Neck harness','Prone neck raises'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Neck strain','Cervicogenic headache'] },
  levator_scapulae: { id:'levator_scapulae', name:'Levator Scapulae', icon:'🔷', region:'neck', group:'Neck/Shoulder Stabilisers', origin:'Transverse processes of C1-C4', insertion:'Medial border of scapula (superior angle)', function:'Elevates scapula, assists in neck lateral flexion and ipsilateral rotation', exercises:['Shrugs','Neck lateral flexion','Overhead press (stabiliser)'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Levator scapulae syndrome','Neck stiffness','Overuse strain'] },

  // SHOULDER
  supraspinatus: { id:'supraspinatus', name:'Supraspinatus', icon:'🟡', region:'shoulder', group:'Rotator Cuff', origin:'Supraspinous fossa of scapula', insertion:'Greater tubercle of humerus (superior facet)', function:'Initiates shoulder abduction (0-15 deg), stabilises humeral head in glenoid', exercises:['Lateral raise','Empty can raise','Cable lateral raise','Band external rotation'], fiber_type:'slow', recovery_hrs:72, common_injuries:['Rotator cuff tear','Shoulder impingement','Tendinopathy'] },
  infraspinatus: { id:'infraspinatus', name:'Infraspinatus', icon:'🟡', region:'shoulder', group:'Rotator Cuff', origin:'Infraspinous fossa of scapula', insertion:'Greater tubercle of humerus (middle facet)', function:'External rotation of shoulder, posterior stabilisation of glenohumeral joint', exercises:['Band external rotation','Cable external rotation','Side-lying external rotation','Face pulls'], fiber_type:'slow', recovery_hrs:72, common_injuries:['Rotator cuff tear','Infraspinatus tendinopathy','Posterior shoulder pain'] },
  teres_minor: { id:'teres_minor', name:'Teres Minor', icon:'🟡', region:'shoulder', group:'Rotator Cuff', origin:'Lateral border of scapula (superior)', insertion:'Greater tubercle of humerus (inferior facet)', function:'External rotation of shoulder, adducts humerus, stabilises glenohumeral joint', exercises:['Face pulls','Band external rotation','Cable Y-raises','Prone external rotation'], fiber_type:'slow', recovery_hrs:72, common_injuries:['Quadrilateral space syndrome','Rotator cuff injury'] },
  subscapularis: { id:'subscapularis', name:'Subscapularis', icon:'🟡', region:'shoulder', group:'Rotator Cuff', origin:'Subscapular fossa of scapula', insertion:'Lesser tubercle of humerus', function:'Internal rotation of shoulder, primary anterior stabiliser of glenohumeral joint', exercises:['Cable internal rotation','Band internal rotation','Bench press (synergist)','Push-ups'], fiber_type:'mixed', recovery_hrs:72, common_injuries:['Subscapularis tear','Internal impingement'] },
  anterior_deltoid: { id:'anterior_deltoid', name:'Anterior Deltoid', icon:'⭐', region:'shoulder', group:'Deltoid', origin:'Anterior lateral clavicle', insertion:'Deltoid tuberosity of humerus', function:'Shoulder flexion, internal rotation, horizontal adduction', exercises:['Overhead press','Front raises','Bench press (synergist)','Arnold press'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Anterior shoulder impingement','Deltoid strain'] },
  medial_deltoid: { id:'medial_deltoid', name:'Medial Deltoid', icon:'⭐', region:'shoulder', group:'Deltoid', origin:'Acromion of scapula', insertion:'Deltoid tuberosity of humerus', function:'Shoulder abduction (15-180 deg with supraspinatus), primary shoulder width muscle', exercises:['Lateral raises','Upright rows','Cable lateral raise','Machine lateral raise'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Shoulder impingement','Deltoid contusion'] },
  posterior_deltoid: { id:'posterior_deltoid', name:'Posterior Deltoid', icon:'⭐', region:'shoulder', group:'Deltoid', origin:'Spine of scapula', insertion:'Deltoid tuberosity of humerus', function:'Shoulder extension, external rotation, horizontal abduction', exercises:['Face pulls','Rear delt fly','Reverse pec deck','Band pull-aparts'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Posterior shoulder strain','Rear delt impingement'] },
  teres_major: { id:'teres_major', name:'Teres Major', icon:'🔵', region:'shoulder', group:'Shoulder Muscles', origin:'Posterior surface of scapula (inferior angle)', insertion:'Medial lip of intertubercular sulcus of humerus', function:'Internal rotation, extension, adduction of shoulder; assists latissimus dorsi', exercises:['Pull-ups','Lat pulldown','Dumbbell row','Straight-arm pulldown'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Teres major strain','Posterior shoulder pain'] },
  coracobrachialis: { id:'coracobrachialis', name:'Coracobrachialis', icon:'🔵', region:'shoulder', group:'Shoulder Muscles', origin:'Coracoid process of scapula', insertion:'Medial surface of humerus (mid-shaft)', function:'Shoulder flexion and adduction; stabilises humeral head', exercises:['Cable crossover','Chest fly','Pull-ups (synergist)'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Musculocutaneous nerve entrapment','Strain (rare)'] },
  serratus_anterior: { id:'serratus_anterior', name:'Serratus Anterior', icon:'🔷', region:'shoulder', group:'Scapular Stabilisers', origin:'Outer surfaces of ribs 1-8', insertion:'Medial border of scapula (costal surface)', function:'Protracts and upwardly rotates scapula; essential for overhead movement; prevents winging', exercises:['Serratus push-ups','Overhead press (synergist)','Landmine press','Cable punches'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Winged scapula','Long thoracic nerve palsy','Serratus strain'] },

  // CHEST
  pec_major_clavicular: { id:'pec_major_clavicular', name:'Pec Major (Clavicular)', icon:'🔶', region:'chest', group:'Pectoralis Major', origin:'Medial half of clavicle', insertion:'Lateral lip of intertubercular sulcus of humerus', function:'Shoulder flexion, horizontal adduction, internal rotation; upper chest emphasis', exercises:['Incline bench press','Incline dumbbell fly','High cable fly','Incline push-ups'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Pec major tear (rare)','Anterior shoulder pain','Bench press injury'] },
  pec_major_sternal: { id:'pec_major_sternal', name:'Pec Major (Sternal)', icon:'🔶', region:'chest', group:'Pectoralis Major', origin:'Anterior sternum, costal cartilages ribs 2-6', insertion:'Lateral lip of intertubercular sulcus of humerus', function:'Shoulder adduction, horizontal adduction, internal rotation; lower/mid chest emphasis', exercises:['Flat bench press','Dumbbell fly','Cable crossover','Dips'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Pec major tear (bench press)','Pec strain','Shoulder impingement secondary'] },
  pectoralis_minor: { id:'pectoralis_minor', name:'Pectoralis Minor', icon:'🔶', region:'chest', group:'Chest Deep', origin:'Anterior surfaces of ribs 3-5', insertion:'Coracoid process of scapula', function:'Protracts, depresses and downwardly rotates scapula; assists forced inspiration', exercises:['Push-ups (synergist)','Bench press (synergist)','Doorway stretch (antagonist)'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Pec minor syndrome (nerve entrapment)','Postural tightness'] },

  // BACK
  latissimus_dorsi: { id:'latissimus_dorsi', name:'Latissimus Dorsi', icon:'🔵', region:'back', group:'Superficial Back', origin:'Spinous processes T7-L5, thoracolumbar fascia, iliac crest, inferior 3-4 ribs', insertion:'Floor of intertubercular sulcus of humerus', function:'Shoulder extension, adduction, internal rotation; spinal stabilisation; creates V-taper', exercises:['Pull-ups','Lat pulldown','Barbell row','Single-arm dumbbell row','Straight-arm pulldown'], fiber_type:'mixed', recovery_hrs:72, common_injuries:['Lat strain','Teres major strain','Low back strain (secondary)'] },
  rhomboid_major: { id:'rhomboid_major', name:'Rhomboid Major', icon:'🔷', region:'back', group:'Mid Back', origin:'Spinous processes T2-T5', insertion:'Medial border of scapula (between spine and inferior angle)', function:'Retracts and elevates scapula; downwardly rotates scapula', exercises:['Seated cable row','Face pulls','Band pull-aparts','T-bar row','Dumbbell row'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Rhomboid strain','Mid-back pain','Overuse from poor posture'] },
  rhomboid_minor: { id:'rhomboid_minor', name:'Rhomboid Minor', icon:'🔷', region:'back', group:'Mid Back', origin:'Ligamentum nuchae, spinous processes C7-T1', insertion:'Medial border of scapula at spine', function:'Retracts scapula, assists in scapular elevation and downward rotation', exercises:['Face pulls','Band pull-aparts','Cable rows','Prone cobra'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Rhomboid strain','Interscapular pain'] },
  middle_trapezius: { id:'middle_trapezius', name:'Middle Trapezius', icon:'🔷', region:'back', group:'Trapezius', origin:'Spinous processes C7-T3', insertion:'Acromion and spine of scapula', function:'Retracts scapula (draws it toward spine), stabilises scapula during arm movements', exercises:['Seated row','Face pulls','Band pull-aparts','Prone T-raise','Bent-over row'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Middle trap strain','Postural overuse','Interscapular ache'] },
  lower_trapezius: { id:'lower_trapezius', name:'Lower Trapezius', icon:'🔷', region:'back', group:'Trapezius', origin:'Spinous processes T4-T12', insertion:'Spine of scapula (medial)', function:'Depresses and upwardly rotates scapula; critical for overhead stability', exercises:['Prone Y-raise','Cable Y-raise','Wall slide','Band overhead press','Lat pulldown (synergist)'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Lower trap weakness (shoulder impingement contributor)','Postural dysfunction'] },
  iliocostalis: { id:'iliocostalis', name:'Iliocostalis (Erector Spinae)', icon:'⚡', region:'back', group:'Erector Spinae', origin:'Iliac crest, sacrum', insertion:'Angles of lower ribs, transverse processes (cervical)', function:'Bilateral: extends and maintains upright spine. Unilateral: lateral flexion', exercises:['Deadlift','Back extension','Barbell row (isometric)','Good morning'], fiber_type:'slow', recovery_hrs:72, common_injuries:['Erector spinae strain','Acute low back pain'] },
  longissimus: { id:'longissimus', name:'Longissimus (Erector Spinae)', icon:'⚡', region:'back', group:'Erector Spinae', origin:'Sacrum, ilium, spinous processes (lumbar)', insertion:'Transverse processes (thoracic and cervical), mastoid process', function:'Spinal extension, lateral flexion; maintaining upright posture', exercises:['Deadlift','Hyperextension','Good morning','Romanian deadlift'], fiber_type:'slow', recovery_hrs:72, common_injuries:['Low back strain','Myofascial pain'] },
  spinalis: { id:'spinalis', name:'Spinalis (Erector Spinae)', icon:'⚡', region:'back', group:'Erector Spinae', origin:'Spinous processes (upper lumbar, lower thoracic)', insertion:'Spinous processes (upper thoracic, cervical)', function:'Spinal extension, stabilises vertebral column, assists with lateral flexion', exercises:['Deadlift (synergist)','Hyperextensions','Back extensions','Barbell rows'], fiber_type:'slow', recovery_hrs:72, common_injuries:['Spinal strain','Vertebral compression (severe cases)'] },
  multifidus: { id:'multifidus', name:'Multifidus', icon:'⚡', region:'back', group:'Deep Spinal Stabilisers', origin:'Sacrum, iliac spine, transverse processes (L5-C4)', insertion:'Spinous processes 2-4 vertebrae superiorly', function:'Segmental spinal stabilisation, resists rotational forces, maintains spinal curvature', exercises:['Bird-dog','Dead bug','Pallof press','Plank','McGill curl-up'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Chronic low back pain (key contributor when inhibited)','Disc herniation (associated weakness)'] },
  quadratus_lumborum: { id:'quadratus_lumborum', name:'Quadratus Lumborum', icon:'⚡', region:'back', group:'Deep Spinal Stabilisers', origin:'Posterior iliac crest, iliolumbar ligament', insertion:'12th rib, transverse processes L1-L4', function:'Lateral flexion of lumbar spine, fixes 12th rib during respiration, stabilises lumbar spine', exercises:['Side plank','Lateral sled drag','DB side bend','Unilateral farmer carry'], fiber_type:'slow', recovery_hrs:72, common_injuries:['QL strain (common low back pain source)','Hip hike compensation patterns'] },

  // ARMS
  biceps_long: { id:'biceps_long', name:'Biceps (Long Head)', icon:'💪', region:'arms', group:'Biceps', origin:'Supraglenoid tubercle of scapula', insertion:'Radial tuberosity, bicipital aponeurosis', function:'Elbow flexion, forearm supination, weak shoulder flexion; long head creates outer bicep peak', exercises:['Barbell curl','Incline dumbbell curl','Hammer curl','Spider curl'], fiber_type:'fast', recovery_hrs:48, common_injuries:['Biceps tendon tear (proximal)','Bicipital tendinitis','Bicep strain'] },
  biceps_short: { id:'biceps_short', name:'Biceps (Short Head)', icon:'💪', region:'arms', group:'Biceps', origin:'Coracoid process of scapula', insertion:'Radial tuberosity, bicipital aponeurosis', function:'Elbow flexion, forearm supination, shoulder adduction; short head adds inner bicep thickness', exercises:['Wide-grip barbell curl','Preacher curl','Cable curl','Concentration curl'], fiber_type:'fast', recovery_hrs:48, common_injuries:['Bicep strain','Bicipital groove tendinitis'] },
  brachialis: { id:'brachialis', name:'Brachialis', icon:'💪', region:'arms', group:'Elbow Flexors', origin:'Anterior humerus (lower half)', insertion:'Coronoid process and tuberosity of ulna', function:'Strongest elbow flexor regardless of forearm position; largest contributor to arm size', exercises:['Hammer curl','Reverse curl','Cross-body curl','Chin-up (synergist)'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Brachialis strain','Elbow tendinopathy'] },
  brachioradialis: { id:'brachioradialis', name:'Brachioradialis', icon:'💪', region:'arms', group:'Elbow Flexors', origin:'Lateral supracondylar ridge of humerus', insertion:'Styloid process of radius', function:'Elbow flexion in neutral forearm position, assists with forearm supination/pronation', exercises:['Hammer curl','Reverse curl','Zottman curl','Neutral-grip pull-up'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Lateral epicondylitis (secondary)','Forearm strain'] },
  triceps_long: { id:'triceps_long', name:'Triceps (Long Head)', icon:'🔴', region:'arms', group:'Triceps', origin:'Infraglenoid tubercle of scapula', insertion:'Olecranon process of ulna', function:'Elbow extension, shoulder extension and adduction; largest tricep head, gives arm mass', exercises:['Overhead tricep extension','Close-grip bench press','Dips','Skull crusher'], fiber_type:'fast', recovery_hrs:48, common_injuries:['Tricep strain','Distal tricep tendon rupture (rare)'] },
  triceps_lateral: { id:'triceps_lateral', name:'Triceps (Lateral Head)', icon:'🔴', region:'arms', group:'Triceps', origin:'Posterior surface of humerus (upper half, lateral)', insertion:'Olecranon process of ulna', function:'Elbow extension; creates the horseshoe shape on the outer arm', exercises:['Pushdown (rope)','Tricep kickback','Close-grip bench press','Dips'], fiber_type:'fast', recovery_hrs:48, common_injuries:['Lateral tricep strain','Elbow tendinopathy'] },
  triceps_medial: { id:'triceps_medial', name:'Triceps (Medial Head)', icon:'🔴', region:'arms', group:'Triceps', origin:'Posterior surface of humerus (lower half, medial)', insertion:'Olecranon process of ulna', function:'Elbow extension (active in all ranges); deepest head, provides tricep foundation', exercises:['Reverse pushdown','Close-grip bench press','All tricep exercises (synergist)'], fiber_type:'fast', recovery_hrs:48, common_injuries:['Medial epicondyle impingement','Tricep strain'] },
  anconeus: { id:'anconeus', name:'Anconeus', icon:'🔴', region:'arms', group:'Elbow Extensors', origin:'Posterior lateral epicondyle of humerus', insertion:'Lateral olecranon and posterior ulna', function:'Assists triceps in elbow extension, stabilises elbow joint, abducts ulna in pronation', exercises:['Tricep exercises (synergist)','Pushdown','Overhead press (synergist)'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Lateral epicondylitis (tennis elbow)','Elbow instability'] },
  fcr: { id:'fcr', name:'Flexor Carpi Radialis', icon:'🤚', region:'arms', group:'Forearm Flexors', origin:'Medial epicondyle of humerus', insertion:'Base of 2nd metacarpal', function:'Wrist flexion and radial deviation, assists in forearm pronation', exercises:['Wrist curl','Barbell wrist flexion','Reverse wrist curl (antagonist)'], fiber_type:'slow', recovery_hrs:48, common_injuries:["Golfer's elbow (medial epicondylitis)",'Wrist flexor tendinitis'] },
  fcu: { id:'fcu', name:'Flexor Carpi Ulnaris', icon:'🤚', region:'arms', group:'Forearm Flexors', origin:'Medial epicondyle, posterior ulna', insertion:'Pisiform, hamate, base of 5th metacarpal', function:'Wrist flexion and ulnar deviation (adduction)', exercises:['Wrist curl','Ulnar deviation exercise','Grip training'], fiber_type:'slow', recovery_hrs:48, common_injuries:["Golfer's elbow",'Cubital tunnel syndrome (associated)'] },
  palmaris_longus: { id:'palmaris_longus', name:'Palmaris Longus', icon:'🤚', region:'arms', group:'Forearm Flexors', origin:'Medial epicondyle of humerus', insertion:'Flexor retinaculum and palmar aponeurosis', function:'Wrist flexion, tenses palmar fascia; absent in ~14% of people', exercises:['Wrist curl','Farmer carry','Grip exercises'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Medial epicondylitis','Wrist flexor strain'] },
  fds: { id:'fds', name:'Flexor Digitorum Superficialis', icon:'🤚', region:'arms', group:'Forearm Flexors', origin:'Medial epicondyle, coronoid process, anterior radius', insertion:'Middle phalanges of fingers 2-5', function:'Flexes fingers (PIP joints), assists wrist flexion; key grip strength muscle', exercises:['Dead hang','Farmer carry','Finger curl','Grip trainer'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Flexor pulley injury (rock climbing)','Trigger finger',"Golfer's elbow"] },
  ecrl: { id:'ecrl', name:'Extensor Carpi Radialis Longus', icon:'✋', region:'arms', group:'Forearm Extensors', origin:'Lateral supracondylar ridge of humerus', insertion:'Base of 2nd metacarpal', function:'Wrist extension and radial deviation; co-activates with gripping', exercises:['Reverse wrist curl','Reverse barbell curl','Wrist roller'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Tennis elbow (lateral epicondylitis)','Wrist extensor tendinitis'] },
  ecrb: { id:'ecrb', name:'Extensor Carpi Radialis Brevis', icon:'✋', region:'arms', group:'Forearm Extensors', origin:'Lateral epicondyle of humerus', insertion:'Base of 3rd metacarpal', function:'Wrist extension; primary muscle involved in tennis elbow', exercises:['Reverse wrist curl','Wrist extension','Wrist roller'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Tennis elbow (most common site)','Chronic wrist extensor pain'] },
  ecu: { id:'ecu', name:'Extensor Carpi Ulnaris', icon:'✋', region:'arms', group:'Forearm Extensors', origin:'Lateral epicondyle of humerus, posterior ulna', insertion:'Base of 5th metacarpal', function:'Wrist extension and ulnar deviation', exercises:['Reverse wrist curl','Reverse barbell curl','Ulnar deviation exercise'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Tennis elbow','ECU tendon subluxation (wrist rotation)'] },

  // CORE
  rectus_abdominis: { id:'rectus_abdominis', name:'Rectus Abdominis', icon:'🟩', region:'core', group:'Anterior Core', origin:'Pubic symphysis and crest', insertion:'Xiphoid process, costal cartilages of ribs 5-7', function:'Spinal flexion, posterior pelvic tilt, compresses abdominal contents, assists in forced expiration', exercises:['Crunch','Sit-up','Hanging knee raise','Ab wheel rollout','Cable crunch'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Ab strain','Diastasis recti','Sports hernia'] },
  external_oblique: { id:'external_oblique', name:'External Oblique', icon:'🟩', region:'core', group:'Lateral Core', origin:'Outer surfaces of ribs 5-12', insertion:'Iliac crest, linea alba, inguinal ligament', function:'Ipsilateral lateral flexion, contralateral rotation, bilateral spinal flexion; key in bracing', exercises:['Woodchopper','Side plank','Russian twist','Pallof press','Bicycle crunch'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Oblique strain (rotational sports)','Sports hernia'] },
  internal_oblique: { id:'internal_oblique', name:'Internal Oblique', icon:'🟩', region:'core', group:'Lateral Core', origin:'Thoracolumbar fascia, iliac crest, inguinal ligament', insertion:'Costal cartilages of ribs 8-12, linea alba', function:'Ipsilateral rotation and lateral flexion, assists spinal flexion, compresses abdomen', exercises:['Pallof press','Side plank','Woodchopper','Oblique crunch','Cable rotation'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Internal oblique strain','Sports hernia'] },
  transverse_abdominis: { id:'transverse_abdominis', name:'Transverse Abdominis', icon:'🟩', region:'core', group:'Deep Core', origin:'Thoracolumbar fascia, iliac crest, inguinal ligament, ribs 7-12', insertion:'Linea alba, pubic crest', function:'Compresses abdomen, increases intra-abdominal pressure for spinal stability; deepest core layer', exercises:['Dead bug','Plank','Hollow body hold','Pallof press','Bracing drills'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Chronic low back pain (inhibition)','Hernia risk when weak'] },
  diaphragm: { id:'diaphragm', name:'Diaphragm', icon:'🫁', region:'core', group:'Deep Core', origin:'Xiphoid process, costal margins, lumbar vertebrae (L1-L3)', insertion:'Central tendon', function:'Primary breathing muscle; descends on inspiration. Key for intra-abdominal pressure in bracing', exercises:['Diaphragmatic breathing','Crocodile breathing','Bracing drills','Deadlift (bracing synergist)'], fiber_type:'slow', recovery_hrs:24, common_injuries:['Diaphragm strain (rare)','Side stitch during exercise'] },
  pelvic_floor: { id:'pelvic_floor', name:'Pelvic Floor', icon:'🟩', region:'core', group:'Deep Core', origin:'Pubis, ischium, coccyx', insertion:'Perineal body, coccyx', function:'Supports pelvic organs, controls continence, contributes to intra-abdominal pressure with diaphragm and TVA', exercises:['Kegel exercises','Diaphragmatic breathing','Squats (functional activation)','Deadlift (co-contraction)'], fiber_type:'slow', recovery_hrs:24, common_injuries:['Pelvic floor dysfunction','Stress incontinence (weakness)','Pelvic pain (hypertonicity)'] },
  psoas_major: { id:'psoas_major', name:'Psoas Major', icon:'🟨', region:'core', group:'Hip Flexors', origin:'Transverse processes and bodies of T12-L5', insertion:'Lesser trochanter of femur', function:'Hip flexion, external rotation; stabilises lumbar spine when bilateral; postural muscle prone to tightness', exercises:['Hip flexor stretch','Lunge','Hanging leg raise','Step-ups','Reverse crunch'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Hip flexor strain','Psoas bursitis','Low back pain (tightness contribution)'] },
  iliacus: { id:'iliacus', name:'Iliacus', icon:'🟨', region:'core', group:'Hip Flexors', origin:'Iliac fossa', insertion:'Lesser trochanter of femur (with psoas = iliopsoas)', function:'Hip flexion, assists in hip external rotation; stabilises hip joint', exercises:['Squat (synergist)','Hip flexor stretch','Leg raise','Running (hip drive)'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Iliopsoas strain','Snapping hip syndrome','Femoral nerve irritation'] },

  // HIPS/GLUTES
  gluteus_maximus: { id:'gluteus_maximus', name:'Gluteus Maximus', icon:'🍑', region:'hips', group:'Glutes', origin:'Posterior ilium, sacrum, coccyx, thoracolumbar fascia', insertion:'Gluteal tuberosity of femur, iliotibial band', function:'Hip extension, external rotation, posterior pelvic tilt; primary mover in squats, deadlifts, sprinting', exercises:['Squat','Deadlift','Hip thrust','Romanian deadlift','Glute bridge'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Glute strain','Piriformis syndrome (associated)','Hip bursitis'] },
  gluteus_medius: { id:'gluteus_medius', name:'Gluteus Medius', icon:'🍑', region:'hips', group:'Glutes', origin:'Outer surface of ilium (between anterior and posterior gluteal lines)', insertion:'Greater trochanter of femur (lateral surface)', function:'Hip abduction, internal rotation (anterior fibres), stabilises pelvis during single-leg loading', exercises:['Hip abduction','Clamshell','Single-leg squat','Lateral band walk','Hip thrust'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Glute med tear','Trendelenburg gait (weakness)','Lateral hip pain','IT band syndrome (associated)'] },
  gluteus_minimus: { id:'gluteus_minimus', name:'Gluteus Minimus', icon:'🍑', region:'hips', group:'Glutes', origin:'Outer surface of ilium (between anterior and inferior gluteal lines)', insertion:'Greater trochanter of femur (anterior surface)', function:'Hip abduction and internal rotation; pelvic stabilisation in single-leg stance', exercises:['Hip abduction','Clamshell','Single-leg press','Lateral band walk'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Lateral hip tendinopathy','Trochanteric bursitis'] },
  piriformis: { id:'piriformis', name:'Piriformis', icon:'🔵', region:'hips', group:'Deep Hip External Rotators', origin:'Anterior sacrum (S2-S4)', insertion:'Greater trochanter of femur', function:'External rotation of hip (neutral), abduction of flexed hip; closely related to sciatic nerve', exercises:['Figure-4 stretch','Hip external rotation','Pigeon pose','Clamshell'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Piriformis syndrome (sciatic nerve irritation)','Deep gluteal pain'] },
  gemellus_superior: { id:'gemellus_superior', name:'Gemellus Superior', icon:'🔵', region:'hips', group:'Deep Hip External Rotators', origin:'Ischial spine', insertion:'Medial surface of greater trochanter', function:'Hip external rotation, assists in hip abduction; part of short external rotators group', exercises:['Hip external rotation','Clamshell','Figure-4 stretch'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Deep gluteal pain','Hip external rotator strain'] },
  gemellus_inferior: { id:'gemellus_inferior', name:'Gemellus Inferior', icon:'🔵', region:'hips', group:'Deep Hip External Rotators', origin:'Ischial tuberosity', insertion:'Medial surface of greater trochanter', function:'Hip external rotation, stabilises femoral head in acetabulum', exercises:['Hip external rotation','Clamshell','Seated hip rotations'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Hip strain','Ischiofemoral impingement'] },
  obturator_internus: { id:'obturator_internus', name:'Obturator Internus', icon:'🔵', region:'hips', group:'Deep Hip External Rotators', origin:'Internal surface of obturator membrane and surrounding bone', insertion:'Greater trochanter of femur', function:'Hip external rotation; also assists in hip abduction when hip is flexed', exercises:['Clamshell','Hip external rotation','Pigeon stretch','Figure-4 stretch'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Deep hip pain','Obturator nerve entrapment'] },
  obturator_externus: { id:'obturator_externus', name:'Obturator Externus', icon:'🔵', region:'hips', group:'Deep Hip External Rotators', origin:'External surface of obturator membrane, pubic rami, ischium', insertion:'Trochanteric fossa of femur', function:'Hip external rotation, stabilises femoral head', exercises:['Hip external rotation','Sumo squat (synergist)','Lateral lunge'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Adductor/groin pain (associated)','Hip impingement'] },
  tfl: { id:'tfl', name:'Tensor Fasciae Latae', icon:'🔵', region:'hips', group:'Hip Abductors', origin:'Anterior iliac crest, ASIS', insertion:'Iliotibial band (IT band)', function:'Hip flexion, abduction, internal rotation; tenses IT band', exercises:['Hip abduction','Lateral band walk','Squat (synergist)','Hip flexion exercises'], fiber_type:'slow', recovery_hrs:48, common_injuries:['IT band syndrome','TFL tightness','Trochanteric bursitis'] },

  // THIGH
  rectus_femoris: { id:'rectus_femoris', name:'Rectus Femoris', icon:'🦵', region:'legs', group:'Quadriceps', origin:'Anterior inferior iliac spine (AIIS), ilium above acetabulum', insertion:'Patella via quadriceps tendon, tibial tuberosity via patellar ligament', function:'Knee extension AND hip flexion (biarticular); active in kicking and sprinting', exercises:['Squat','Leg extension','Lunge','Running (hip drive)','Leg press'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Rectus femoris strain','Quad strain','Patellar tendinopathy'] },
  vastus_lateralis: { id:'vastus_lateralis', name:'Vastus Lateralis', icon:'🦵', region:'legs', group:'Quadriceps', origin:'Greater trochanter, lateral femoral lip of linea aspera', insertion:'Patella via quadriceps tendon', function:'Knee extension; largest quad head; creates outer quad sweep', exercises:['Leg press (feet close)','Squat','Leg extension','Hack squat'], fiber_type:'fast', recovery_hrs:72, common_injuries:['IT band syndrome (friction against VL)','Quad strain','Patellar tracking issues'] },
  vastus_medialis: { id:'vastus_medialis', name:'Vastus Medialis (VMO)', icon:'🦵', region:'legs', group:'Quadriceps', origin:'Medial femoral lip of linea aspera, medial supracondylar line', insertion:'Patella via quadriceps tendon (medial aspect)', function:'Knee extension; VMO stabilises patella medially; creates inner quad teardrop', exercises:['Close-stance squat','Leg extension (terminal)','Bulgarian split squat','Step-up'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Patellofemoral pain syndrome (VMO weakness)','Patellar dislocation (associated)'] },
  vastus_intermedius: { id:'vastus_intermedius', name:'Vastus Intermedius', icon:'🦵', region:'legs', group:'Quadriceps', origin:'Anterior and lateral femoral shaft', insertion:'Patella via quadriceps tendon (deep)', function:'Knee extension; lies deep to other quads; active in all knee extension ranges', exercises:['Squat','Leg press','Leg extension','Lunge'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Quad strain (deep)','Knee pain (secondary)'] },
  biceps_femoris_long: { id:'biceps_femoris_long', name:'Biceps Femoris (Long Head)', icon:'🦵', region:'legs', group:'Hamstrings', origin:'Ischial tuberosity', insertion:'Head of fibula, lateral condyle of tibia', function:'Knee flexion, hip extension, external rotation of knee (when flexed); biarticular', exercises:['Romanian deadlift','Nordic curl','Leg curl','Good morning'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Hamstring strain (most common at proximal tendon)','Hamstring avulsion'] },
  biceps_femoris_short: { id:'biceps_femoris_short', name:'Biceps Femoris (Short Head)', icon:'🦵', region:'legs', group:'Hamstrings', origin:'Lateral lip of linea aspera', insertion:'Head of fibula', function:'Knee flexion, external rotation of knee; monoarticular (only crosses knee)', exercises:['Leg curl','Nordic curl','Hamstring exercises'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Distal hamstring strain','Biceps femoris tendinopathy (fibular head)'] },
  semitendinosus: { id:'semitendinosus', name:'Semitendinosus', icon:'🦵', region:'legs', group:'Hamstrings', origin:'Ischial tuberosity', insertion:'Medial condyle of tibia (pes anserine)', function:'Knee flexion, hip extension, internal rotation of knee (when flexed)', exercises:['Nordic curl','Romanian deadlift','Leg curl','Sumo deadlift'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Hamstring strain','Pes anserine bursitis'] },
  semimembranosus: { id:'semimembranosus', name:'Semimembranosus', icon:'🦵', region:'legs', group:'Hamstrings', origin:'Ischial tuberosity', insertion:'Posterior medial tibial condyle', function:'Knee flexion, hip extension, internal rotation of knee; posterior knee stabiliser', exercises:['Nordic curl','Stiff-leg deadlift','Leg curl','Glute-ham raise'], fiber_type:'fast', recovery_hrs:72, common_injuries:['Hamstring strain (medial)','Posterior knee pain'] },
  adductor_magnus: { id:'adductor_magnus', name:'Adductor Magnus', icon:'🦵', region:'legs', group:'Adductors', origin:'Ischiopubic ramus, ischial tuberosity', insertion:'Medial femoral lip of linea aspera, adductor tubercle', function:'Hip adduction; posterior part extends hip (acts like a hamstring)', exercises:['Sumo squat','Copenhagen plank','Adductor machine','Romanian deadlift (synergist)'], fiber_type:'mixed', recovery_hrs:72, common_injuries:['Adductor strain (groin pull)','Adductor avulsion'] },
  adductor_longus: { id:'adductor_longus', name:'Adductor Longus', icon:'🦵', region:'legs', group:'Adductors', origin:'Body of pubis (below pubic crest)', insertion:'Middle third of medial lip of linea aspera', function:'Hip adduction, assists in hip flexion from extended position', exercises:['Adductor machine','Sumo squat','Copenhagen plank','Lateral lunge'], fiber_type:'mixed', recovery_hrs:72, common_injuries:['Groin strain (most common adductor injured)','Sports hernia'] },
  adductor_brevis: { id:'adductor_brevis', name:'Adductor Brevis', icon:'🦵', region:'legs', group:'Adductors', origin:'Body and inferior ramus of pubis', insertion:'Pectineal line, proximal linea aspera', function:'Hip adduction, assists in hip flexion and external rotation', exercises:['Adductor machine','Sumo squat','Lateral lunge'], fiber_type:'mixed', recovery_hrs:72, common_injuries:['Groin strain','Adductor tendinopathy'] },
  gracilis: { id:'gracilis', name:'Gracilis', icon:'🦵', region:'legs', group:'Adductors', origin:'Body and inferior ramus of pubis', insertion:'Medial condyle of tibia (pes anserine)', function:'Hip adduction, knee flexion, internal rotation of tibia; only biarticular adductor', exercises:['Copenhagen plank','Adductor machine','Leg curl (synergist)','Sumo squat'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Gracilis strain','Pes anserine bursitis','Groin pain'] },
  pectineus: { id:'pectineus', name:'Pectineus', icon:'🦵', region:'legs', group:'Adductors', origin:'Pectineal line of pubis', insertion:'Pectineal line of femur', function:'Hip adduction and flexion; assists in hip external rotation', exercises:['Adductor machine','Hip flexion','Sumo squat','Lateral lunge'], fiber_type:'mixed', recovery_hrs:48, common_injuries:['Hip flexor strain','Groin pain','Femoral nerve compression'] },

  // LOWER LEG
  gastrocnemius_medial: { id:'gastrocnemius_medial', name:'Gastrocnemius (Medial)', icon:'🦶', region:'legs', group:'Calf', origin:'Medial condyle of femur', insertion:'Posterior calcaneus via Achilles tendon', function:'Plantarflexion, knee flexion (biarticular); creates medial calf mass', exercises:['Standing calf raise','Calf press','Single-leg calf raise','Box jumps'], fiber_type:'fast', recovery_hrs:48, common_injuries:['Calf strain (tennis leg)','Achilles tendinopathy'] },
  gastrocnemius_lateral: { id:'gastrocnemius_lateral', name:'Gastrocnemius (Lateral)', icon:'🦶', region:'legs', group:'Calf', origin:'Lateral condyle of femur', insertion:'Posterior calcaneus via Achilles tendon', function:'Plantarflexion, knee flexion; creates lateral calf prominence', exercises:['Standing calf raise','Calf press','Donkey calf raise','Jump rope'], fiber_type:'fast', recovery_hrs:48, common_injuries:['Calf strain','Achilles tendinopathy'] },
  soleus: { id:'soleus', name:'Soleus', icon:'🦶', region:'legs', group:'Calf', origin:'Posterior head of fibula, soleal line of tibia', insertion:'Posterior calcaneus via Achilles tendon', function:'Plantarflexion — most powerful in seated/knee-flexed position; ~70% slow-twitch postural muscle', exercises:['Seated calf raise','Calf press (knee bent)','Single-leg calf raise'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Soleus strain','Achilles tendinopathy'] },
  plantaris: { id:'plantaris', name:'Plantaris', icon:'🦶', region:'legs', group:'Calf', origin:'Lateral supracondylar line of femur', insertion:'Posterior calcaneus via Achilles tendon (medial)', function:'Weak plantarflexion and knee flexion; vestigial in humans; proprioceptive role', exercises:['Calf raises (synergist)','All lower leg exercises'], fiber_type:'fast', recovery_hrs:48, common_injuries:['Plantaris muscle rupture (often misdiagnosed as calf tear)'] },
  tibialis_anterior: { id:'tibialis_anterior', name:'Tibialis Anterior', icon:'🦶', region:'legs', group:'Lower Leg', origin:'Lateral tibial condyle, proximal 2/3 of lateral tibia, interosseous membrane', insertion:'Medial cuneiform, base of 1st metatarsal', function:'Dorsiflexion and inversion of foot; controls foot lowering during walking (prevents foot slap)', exercises:['Toe raises','Band dorsiflexion','Heel walking','Tibialis raises'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Shin splints (medial tibial stress syndrome)','Anterior compartment syndrome','Tibialis anterior tendinitis'] },
  tibialis_posterior: { id:'tibialis_posterior', name:'Tibialis Posterior', icon:'🦶', region:'legs', group:'Lower Leg', origin:'Posterior interosseous membrane, tibia, fibula', insertion:'Navicular, medial cuneiform, 2nd-4th metatarsals', function:'Foot inversion and plantarflexion; primary dynamic supporter of medial longitudinal arch', exercises:['Single-leg calf raise (inversion)','Theraband inversion','Foot arch exercises'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Posterior tibial tendon dysfunction (flat foot)','Tibialis posterior tendinopathy'] },
  fibularis_longus: { id:'fibularis_longus', name:'Fibularis (Peroneus) Longus', icon:'🦶', region:'legs', group:'Lower Leg', origin:'Head and upper 2/3 of lateral fibula', insertion:'Medial cuneiform, base of 1st metatarsal', function:'Foot eversion and plantarflexion; maintains transverse arch; lateral ankle stabiliser', exercises:['Band eversion','Single-leg balance','Lateral step-up','Ankle circles'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Lateral ankle sprain (peroneal stretch)','Peroneal tendinopathy','Peroneal tendon subluxation'] },
  fibularis_brevis: { id:'fibularis_brevis', name:'Fibularis (Peroneus) Brevis', icon:'🦶', region:'legs', group:'Lower Leg', origin:'Lower 2/3 of lateral fibula', insertion:'Styloid process of 5th metatarsal', function:'Foot eversion; primary lateral ankle stabiliser', exercises:['Band eversion','Ankle stability training','Single-leg balance'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Peroneal tendon tear (at 5th metatarsal)','Lateral ankle sprain','Peroneal subluxation'] },
  flexor_hallucis_longus: { id:'flexor_hallucis_longus', name:'Flexor Hallucis Longus', icon:'🦶', region:'legs', group:'Lower Leg', origin:'Posterior fibula, interosseous membrane', insertion:'Base of distal phalanx of big toe', function:'Flexes big toe, assists plantarflexion and foot inversion; critical for push-off in walking/running', exercises:['Toe curls','Calf raises (synergist)','Single-leg balance'], fiber_type:'slow', recovery_hrs:48, common_injuries:['FHL tendinopathy (dancers/gymnasts)','Trigger toe','Medial ankle pain'] },
  extensor_digitorum_longus: { id:'extensor_digitorum_longus', name:'Extensor Digitorum Longus', icon:'🦶', region:'legs', group:'Lower Leg', origin:'Lateral tibial condyle, upper 3/4 of fibula, interosseous membrane', insertion:'Dorsal surface of middle and distal phalanges, toes 2-5', function:'Dorsiflexion of ankle, extends toes 2-5; assists in foot eversion', exercises:['Toe extension','Band dorsiflexion','Heel walking','Ankle circuit'], fiber_type:'slow', recovery_hrs:48, common_injuries:['Anterior shin splints','Extensor tendinopathy','Anterior compartment syndrome'] }
};

/* ── ANATOMY SCREEN ── */
reg('anatomy', function() {
  var muscles = Object.values(MUSCLE_DB);
  var filter = S.g('settings.anatomyFilter') || 'all';
  var filters = [
    {id:'all',label:'All'},
    {id:'shoulder',label:'Shoulder'},
    {id:'back',label:'Back'},
    {id:'chest',label:'Chest'},
    {id:'arms',label:'Arms'},
    {id:'core',label:'Core'},
    {id:'hips',label:'Hips'},
    {id:'legs',label:'Legs'}
  ];
  var filtered = muscles.filter(function(m) { return filter === 'all' || m.region === filter; });

  return '<div class="topbar"><div class="topbar-title">Muscle Anatomy</div></div>' +
    '<div style="padding:12px 16px 4px;display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;-webkit-overflow-scrolling:touch">' +
    filters.map(function(f) {
      var active = filter === f.id;
      return '<button onclick="_setSetting(\'settings.anatomyFilter\',\''+f.id+'\');go(\'anatomy\')" style="flex-shrink:0;padding:7px 14px;border-radius:20px;font-size:12px;font-weight:600;cursor:pointer;touch-action:manipulation;white-space:nowrap;border:1px solid '+(active?'var(--c1)':'var(--border)')+';background:'+(active?'var(--c1)':'transparent')+';color:'+(active?'#fff':'var(--txt3)')+'">'+f.label+'</button>';
    }).join('') +
    '</div>' +
    '<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:12px 16px">' +
    filtered.map(function(m) {
      return '<div onclick="showMuscleDetail(\''+m.id+'\')" style="background:var(--bg3);border:1px solid var(--border);border-radius:16px;padding:14px;cursor:pointer;touch-action:manipulation;position:relative;overflow:hidden">' +
        '<div style="position:absolute;top:0;left:0;right:0;height:3px;background:var(--grad)"></div>' +
        '<div style="font-size:20px;margin-bottom:6px">'+m.icon+'</div>' +
        '<div style="font-size:13px;font-weight:700;color:var(--txt);margin-bottom:2px">'+m.name+'</div>' +
        '<div style="font-size:10px;color:var(--txt3);text-transform:uppercase;letter-spacing:0.06em">'+m.region+'</div>' +
        '<div style="margin-top:8px;font-size:11px;color:var(--txt3);line-height:1.4">'+m.function.slice(0,60)+'...</div>' +
        '</div>';
    }).join('') +
    '</div><div style="height:20px"></div>';
});

window.showMuscleDetail = function(id) {
  var m = MUSCLE_DB[id];
  if (!m) return;
  modal('💪 '+m.name,
    '<div style="font-size:11px;color:var(--txt3);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:8px">'+m.region+' · '+m.group+'</div>' +
    '<div style="font-size:13px;color:var(--txt2);line-height:1.6;margin-bottom:12px">'+m.function+'</div>' +
    '<div style="background:var(--bg4);border-radius:12px;padding:12px;margin-bottom:10px">' +
    '<div style="font-size:10px;font-weight:700;color:var(--txt3);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:6px">Origin & Insertion</div>' +
    '<div style="font-size:12px;color:var(--txt2)"><strong style="color:var(--txt)">Origin:</strong> '+m.origin+'</div>' +
    '<div style="font-size:12px;color:var(--txt2);margin-top:4px"><strong style="color:var(--txt)">Insertion:</strong> '+m.insertion+'</div>' +
    '</div>' +
    '<div style="font-size:10px;font-weight:700;color:var(--txt3);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:6px">Best Exercises</div>' +
    '<div style="display:flex;flex-wrap:wrap;gap:5px;margin-bottom:12px">'+m.exercises.map(function(e){return '<div style="background:rgba(var(--c1-rgb),0.1);border:1px solid rgba(var(--c1-rgb),0.2);border-radius:8px;padding:4px 10px;font-size:11px;color:var(--c1)">'+e+'</div>';}).join('')+'</div>' +
    '<div style="font-size:10px;font-weight:700;color:var(--txt3);text-transform:uppercase;letter-spacing:0.08em;margin-bottom:6px">Common Injuries</div>' +
    '<div style="display:flex;flex-wrap:wrap;gap:5px;margin-bottom:12px">'+m.common_injuries.map(function(i){return '<div style="background:rgba(255,69,58,0.1);border:1px solid rgba(255,69,58,0.2);border-radius:8px;padding:4px 10px;font-size:11px;color:#ff453a">'+i+'</div>';}).join('')+'</div>' +
    '<div style="display:flex;gap:8px"><div style="flex:1;background:var(--bg4);border-radius:10px;padding:10px;text-align:center"><div style="font-size:18px;font-weight:800;color:var(--txt)">'+m.recovery_hrs+'h</div><div style="font-size:10px;color:var(--txt3)">Recovery</div></div>' +
    '<div style="flex:1;background:var(--bg4);border-radius:10px;padding:10px;text-align:center"><div style="font-size:12px;font-weight:700;color:var(--txt)">'+m.fiber_type+'</div><div style="font-size:10px;color:var(--txt3)">Fiber Type</div></div></div>',
    '<button class="btn btn-ghost" onclick="closeModal()">Close</button>'
  );
};
